<DOCTYPE html>
	<html>
	<head>
     <title>php</title>
	</head>
	<body>
    <?Php
    echo strlen("uma ganesh patil");
    echo "<br>";
    echo str_word_count("uma ganesh");
    echo "<br>";
    echo strrev("uma");
    echo "<br>";
    echo strpos("uma patil", "patil");
    echo "<br>";
    echo str_repeat("uma", "6");
    echo "<br>";
    echo str_replace("yelpale", "patil", "uma yelpale");
    echo "<br>";
    echo addcslashes("Hello World!","W");
    echo "<br>";
    echo addslashes('What does "yolo" mean?');
    echo "<br>";
    echo bin2hex("Hello World!");
    echo "<br>";
    echo chr(52); // Decimal value
    echo "<br>";
    echo chr(052); // Octal value
    echo "<br>";
    echo chr(0x52); // Hex value
    echo "<br>";
    echo chunk_split("umaganesh",2,".");
    echo "<br>";
    echo convert_cyr_string("Hello world! æøå",'w','a');
    echo "<br>";
    echo convert_uudecode(",2&5L;&\@=V]R;&0A `");
    echo "<br>";
    echo convert_uuencode("Hello world");
    echo "<br>";
    echo count_chars("uma",3);
    echo "<br>";
    print_r (explode(" ","uma ganesh patil"));
    echo "<br>";
    print_r (get_html_translation_table());
    echo "<br>";
    echo hebrev("� ���� �����");
    echo "<br>";
    echo hebrevc("� ���� �����\n� ���� �����");//hebrew characters
    echo "<br>";
    echo html_entity_decode('&lt;a href=&quot;https://www.w3schools.com&quot;&gt;w3schools.com&lt;/a&gt;');
    echo "<br>";
    echo htmlentities('<a href="https://www.w3schools.com">Go to w3schools.com</a>');
    echo "<br>";
    echo join(" ",array('Hello','World!','Beautiful','Day!'));
    echo "<br>";
    echo implode(" ",array('Hello','World!','Beautiful','Day!'));
    echo "<br>";
    echo htmlspecialchars("This is some <b>bold</b> text.");
    echo "<br>";
    echo htmlspecialchars_decode("This is some &lt;b&gt;bold&lt;/b&gt; text.");
    echo "<br>";
    echo wordwrap("uma ganesh patil at.po shevate tal pandharpur dist.solapur",5,"<br>\n");
    echo "<br>";
    echo lcfirst("Uma");
    echo "<br>";
    echo levenshtein("Hello World","ello World");
    echo "<br>";
    echo levenshtein("Hello World","ello World",10,20,30);
    echo "<br>";
    echo ltrim("Hello uma","Hello");
    echo "<br>";
    echo md5("uma");
    echo "<br>";
    echo metaphone("uma");
    echo "<br>";
    echo nl2br("One line.\nAnother line.");
    echo "<br>";
    echo number_format("1000000")."<br>";
    echo number_format("1000000",2)."<br>";
    echo number_format("1000000",2,",",".");
    echo "<br>";
    echo ord("hello");
    echo "<br>";
    printf("There are %u million bicycles in %s.",5,"uma patil");
    echo "<br>";
    echo quoted_printable_decode("Hello=0Aworld.");
    echo "<br>";
    echo quotemeta("Hello world. (can you hear me?)");
    echo "<br>";
    echo rtrim("Hello world!","World!");
    echo "<br>";
    echo setlocale(LC_ALL,NULL);
    echo "<br>";
    echo sha1("uma");
    echo "<br>";
    echo similar_text("Hello World","Hello Peter");
    echo "<br>";
    echo soundex("uma");
    echo "<br>";
    echo str_ireplace("WORLD","Peter","Hello world!");
    echo "<br>";
    echo str_pad("uma",20,".");
    echo "<br>";
    echo str_rot13("Hello World");
    echo "<br>";
    echo str_rot13("Uryyb Jbeyq");
    echo "<br>";
    echo str_shuffle("Hello World");
    echo "<br>";
    print_r(str_split("Hello"));
    echo "<br>";
    echo strcasecmp("Hello world!","HELLO WORLD!");
    echo "<br>";
    echo strchr("Hello world!","world");
    echo "<br>";
    echo strncmp("Hello world!","Hello earth!",6);
    echo "<br>";
    echo strpbrk("Hello world!","oe");
    echo "<br>";
    echo strcspn("Hello world!","w");
    echo "<br>";
    echo strcmp("Hello world!","Hello world!");
    echo "<br>";
    echo strip_tags("Hello <b>world!</b>");
    echo "<br>";
    echo stripcslashes("Hello \World!");
    echo "<br>";
    echo stripslashes("Who\'s Peter Griffin?");
    echo "<br>";
    echo stripos("I love php, I love php too!","PHP");
    echo "<br>";
    echo stristr("Hello world!","WORLD");
    echo "<br>";
    echo strnatcasecmp("2Hello world!","10Hello WORLD!");
    echo "<br>";
	echo strnatcasecmp("10Hello world!","2Hello WORLD!");
    echo "<br>";
    echo strnatcmp("2Hello world!","10Hello world!");
	echo "<br>";
	echo strnatcmp("10Hello world!","2Hello world!");
    echo "<br>";
    echo strripos("I love php, I love php too!","PHP");
    echo "<br>";
    echo strrpos("I love php, I love php too!","php");
    echo "<br>";
    echo strstr("Hello world!","world");
    echo "<br>";
    echo strspn("Hello world!","kHlleo");
    echo "<br>";
    echo strtolower("Hello WORLD.");
    echo "<br>";
    echo strtoupper("uma");
    echo "<br>";
    echo strtr("Hilla Warld","ia","eo");
    echo "<br>";
    echo substr("Hello world",6);
    echo "<br>";
    echo substr_compare("Hello world","Hello world",0);
    echo "<br>";
    echo substr_count("Hello world. The world is nice","world");
    echo "<br>";
    echo substr_replace("Hello","world",0);
    echo "<br>";
    echo trim("Hello world","Hed!");
    echo "<br>";
    echo ucfirst("hello world!");
    echo "<br>";
    echo ucwords("hello world");
    echo "<br>";
    vprintf("There are %u million bicycles in %s.",array(2,"india"));
    echo "<br>";
    ?>
	</body>
	</html>